# Script to append new method to scientific_research.py

file_path = r"modules\scientific_research.py"

new_method = '''    
    def save_books_to_folder(self, books, topic, output_dir=None):
        """
        Download books and save them as Word documents in a "related_book" folder
        
        Args:
            books: List of book dictionaries with metadata
            topic: The research topic (for keyword extraction)
            output_dir: Base output directory (defaults to current directory)
        
        Returns:
            List of successfully saved book file paths
        """
        if not DOCX_AVAILABLE:
            print(f"{Fore.YELLOW}⚠ python-docx not installed. Cannot save books as Word documents.{Style.RESET_ALL}")
            print(f"{Fore.YELLOW}   Install with: pip install python-docx{Style.RESET_ALL}")
            return []
        
        if not books:
            print(f"{Fore.YELLOW}⚠ No books to save{Style.RESET_ALL}")
            return []
        
        # Create "related_book" folder
        if output_dir is None:
            output_dir = os.getcwd()
        
        book_folder = os.path.join(output_dir, "related_book")
        
        try:
            os.makedirs(book_folder, exist_ok=True)
            print(f"{Fore.GREEN}✓ Created folder: {book_folder}{Style.RESET_ALL}")
        except Exception as e:
            print(f"{Fore.RED}✗ Could not create folder: {e}{Style.RESET_ALL}")
            return []
        
        saved_files = []
        
        for i, book in enumerate(books, 1):
            try:
                print(f"\\n{Fore.CYAN}📕 Processing book {i}/{len(books)}: {book['title']}{Style.RESET_ALL}")
                
                # Try to download book text if ISBN is available
                book_text = None
                if book.get('isbn'):
                    book_text = self.download_book_text(book['isbn'])
                
                # Create Word document
                doc = Document()
                
                # Add title
                title = doc.add_heading(book['title'], 0)
                title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
                
                # Add metadata
                doc.add_paragraph()
                meta_para = doc.add_paragraph()
                meta_para.add_run(f"Author: ").bold = True
                meta_para.add_run(book.get('author', 'Unknown'))
                meta_para.add_run('\\n')
                
                meta_para.add_run(f"Year: ").bold = True
                meta_para.add_run(str(book.get('year', 'N/A')))
                meta_para.add_run('\\n')
                
                if book.get('isbn'):
                    meta_para.add_run(f"ISBN: ").bold = True
                    meta_para.add_run(book['isbn'])
                    meta_para.add_run('\\n')
                
                doc.add_paragraph()
                doc.add_heading('Content', 1)
                
                # Add book content or excerpts
                if book_text:
                    # Extract relevant passages
                    excerpts = self.extract_book_insights(book_text, topic, max_chars=5000)
                    
                    if excerpts:
                        # Add excerpts header
                        doc.add_paragraph().add_run('Relevant Excerpts:').italic = True
                        doc.add_paragraph()
                        
                        # Add excerpts (split into paragraphs)
                        for excerpt in excerpts.split('\\n\\n'):
                            if excerpt.strip():
                                doc.add_paragraph(excerpt.strip())
                    else:
                        # If no relevant excerpts, add first 5000 chars
                        content_text = book_text[:5000] if len(book_text) > 5000 else book_text
                        doc.add_paragraph(content_text)
                        
                        if len(book_text) > 5000:
                            doc.add_paragraph().add_run(f"\\n[Truncated - Full book is {len(book_text)} characters]").italic = True
                else:
                    # No text available
                    note = doc.add_paragraph()
                    note.add_run("Note: ").bold = True
                    note.add_run("Full book text not available from Internet Archive. ")
                    note.add_run("This document contains only metadata.")
                
                # Add footer
                doc.add_paragraph()
                footer = doc.add_paragraph()
                footer.add_run("\\n" + "="*50 + "\\n").font.color.rgb = RGBColor(150, 150, 150)
                footer_text = footer.add_run("Generated by FlashPoint AI - Super Research Mode")
                footer_text.font.size = Pt(9)
                footer_text.font.color.rgb = RGBColor(100, 100, 100)
                
                # Save document
                # Clean filename (remove invalid characters)
                safe_title = "".join(c for c in book['title'] if c.isalnum() or c in (' ', '-', '_')).strip()
                safe_title = safe_title[:50]  # Limit length
                
                if not safe_title:
                    safe_title = f"book_{i}"
                
                filename = f"{safe_title}.docx"
                filepath = os.path.join(book_folder, filename)
                
                doc.save(filepath)
                saved_files.append(filepath)
                
                print(f"{Fore.GREEN}  ✓ Saved: {filename}{Style.RESET_ALL}")
                
            except Exception as e:
                print(f"{Fore.RED}  ✗ Failed to save book: {e}{Style.RESET_ALL}")
                continue
        
        print(f"\\n{Fore.GREEN}✓ Successfully saved {len(saved_files)} book(s) to: {book_folder}{Style.RESET_ALL}")
        return saved_files
'''

# Read the file
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Append the new method (the file ends with a newline, so we need to add it before the method)
if not content.endswith('\n'):
    content += '\n'

content += new_method

# Write back
with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("✓ Successfully appended save_books_to_folder method to scientific_research.py")
